[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run deploy:start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[deploy.healthcheck]]
path = "/health"
timeout = 100
interval = 60
